# Final Project Machine Learning Python

In [43]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn import preprocessing
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn import svm
import sklearn.tree as tree
%matplotlib inline

In [2]:
df = pd.read_csv("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-ML0101EN-SkillUp/labs/ML-FinalAssignment/Weather_Data.csv")
df.head()

Date  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine WindGustDir  \
0  2/1/2008     19.5     22.4      15.6          6.2       0.0           W   
1  2/2/2008     19.5     25.6       6.0          3.4       2.7           W   
2  2/3/2008     21.6     24.5       6.6          2.4       0.1           W   
3  2/4/2008     20.2     22.8      18.8          2.2       0.0           W   
4  2/5/2008     19.7     25.7      77.4          4.8       0.0           W   

   WindGustSpeed WindDir9am WindDir3pm  ...  Humidity9am  Humidity3pm  \
0             41          S        SSW  ...           92           84   
1             41          W          E  ...           83           73   
2             41        ESE        ESE  ...           88           86   
3             41        NNE          E  ...           83           90   
4             41        NNE          W  ...           88           74   

   Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  RainToday  \
0       1017.6       1017.4         8         8     20.7     20.9        Yes   
1       1017.9       1016.4         7         7     22.4     24.8        Yes   
2       1016.7       1015.6         7         8     23.5     23.0        Yes   
3       1014.2       1011.8         8         8     21.4     20.9        Yes   
4       1008.3       1004.8         8         8     22.5     25.5        Yes   

   RainTomorrow  
0           Yes  
1           Yes  
2           Yes  
3           Yes  
4           Yes  

[5 rows x 22 columns]

In [3]:
df_sydney_processed = pd.get_dummies(data=df, columns=['RainToday', 'WindGustDir', 'WindDir9am', 'WindDir3pm'])
df_sydney_processed.replace(['No', 'Yes'], [0,1], inplace=True)
df_sydney_processed.drop('Date',axis=1,inplace=True)
df_sydney_processed = df_sydney_processed.astype(float)

In [4]:
x = df_sydney_processed.drop(columns='RainTomorrow', axis=1)
y = df_sydney_processed['RainTomorrow']

In [5]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split( x, y, test_size=0.2, random_state=10)
print ('Train set:', x_train.shape, y_train.shape)
print ('Test set:', x_test.shape, y_test.shape)

Train set: (2616, 66) (2616,)
Test set: (655, 66) (655,)


In [6]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
LinearReg = LogisticRegression(C=1, solver='liblinear').fit(x_train,y_train)
LinearReg

LogisticRegression(C=1, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)

In [7]:
predict = LinearReg.predict(x_test)
predict[0:5]

array([0., 0., 1., 0., 0.])

In [8]:
LinearRegression_MAE = mean_absolute_error(y_test, predict)
LinearRegression_MSE = mean_squared_error(y_test, predict)
LinearRegression_R2 = r2_score(y_test, predict)
print(LinearRegression_MAE)
print(LinearRegression_MSE)
print(LinearRegression_R2)

0.1618320610687023
0.1618320610687023
0.1988599649219973


# KNN

In [9]:
from sklearn.neighbors import KNeighborsClassifier
k = 4

neigh = KNeighborsClassifier(n_neighbors = k).fit(x_train,y_train)
predict = neigh.predict(x_test)
predict[0:5]

array([0., 0., 1., 0., 0.])

In [10]:
KNN_MAE = mean_absolute_error(y_test, predict)
KNN_MSE = mean_squared_error(y_test, predict)
KNN_R2 = r2_score(y_test, predict)
print(KNN_MAE)
print(KNN_MSE)
print(KNN_R2)

0.18167938931297709
0.18167938931297709
0.10060694175205365


# Desicion Tree

In [18]:
Tree = DecisionTreeClassifier(criterion="entropy", max_depth = 4)
Tree.fit(x_train,y_train)
predict= drugTree.predict(x_test)

In [19]:
Tree_MAE = mean_absolute_error(y_test, predict)
Tree_MSE = mean_squared_error(y_test, predict)
Tree_R2 = r2_score(y_test, predict)
print(Tree_MAE)
print(Tree_MSE)
print(Tree_R2)

0.18167938931297709
0.18167938931297709
0.10060694175205365


# Logisctic Regression

In [26]:
x_train, x_test, y_train, y_test = train_test_split( x, y, test_size=0.2, random_state=1)
print ('Train set:', x_train.shape, y_train.shape)
print ('Test set:', x_test.shape, y_test.shape)

Train set: (2616, 66) (2616,)
Test set: (655, 66) (655,)


In [33]:
LR = LogisticRegression(C=0.01, solver='liblinear').fit(x_train,y_train)
predict = LR.predict(x_test)

In [37]:
LR_MAE = mean_absolute_error(y_test, predict)
LR_MSE = mean_squared_error(y_test, predict)
LR_R2 = r2_score(y_test, predict)
print(LR_MAE)
print(LR_MSE)
print(LR_R2)

0.17251908396946564
0.17251908396946564
0.14022024487140772


# SVM

In [53]:
x_train, x_test, y_train, y_test = train_test_split( x, y, test_size=0.2, random_state=4)
SVM = svm.SVC(kernel='linear')
SVM.fit(x_train, y_train)
predict = SVM.predict(x_test)
predict[0:5]

array([0., 1., 0., 0., 1.])

In [56]:
SVM_MAE = mean_absolute_error(y_test, predict)
SVM_MSE = mean_squared_error(y_test, predict)
SVM_R2 = r2_score(y_test, predict)
print(SVM_MAE)
print(SVM_MSE)
print(SVM_R2)

0.1618320610687023
0.1618320610687023
0.19618875613596365


In [57]:
dict = {'Model' : ['Linear', 'KNN', 'Tree', 'Logist', 'SVM'],
        'MAE' : [LinearRegression_MAE, KNN_MAE, Tree_MAE, LR_MAE, SVM_MAE],
        'MSE' : [LinearRegression_MSE, KNN_MSE, Tree_MSE, LR_MSE, SVM_MSE],
        'R2' : [LinearRegression_R2, KNN_R2, Tree_R2, LR_R2, SVM_R2]}
df = pd.DataFrame(dict)
df

Model       MAE       MSE        R2
0  Linear  0.161832  0.161832  0.198860
1     KNN  0.181679  0.181679  0.100607
2    Tree  0.181679  0.181679  0.100607
3  Logist  0.172519  0.172519  0.140220
4     SVM  0.161832  0.161832  0.196189